apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}  # Update with your image
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: RABBITMQ_URL
              #amqp://myuser:mypassword@rabbitmq.default.svc.cluster.local:5672
              #
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@{{ .Values.rabbitmq.fullnameOverride }}.{{ .Values.rabbitmq.namespaceOverride }}.svc.cluster.local:5672"
            - name: DATABASE_URL
              value: "mongodb+srv://{{ .Values.database.username }}:{{ .Values.database.password }}@cluster0.vfrom.mongodb.net/leetcode"
