apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: {{ .Values.namespace }}  # Adjust the namespace if necessary
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
data:
  #echo -n "amqp://guest:password@localhost:5672/vhost" | base64
  host: YW1xcDovL215dXNlcjpteXBhc3N3b3JkQHJhYmJpdG1xLmxlZXRjb2RlLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=  # Replace with your base64-encoded RabbitMQ URI
