apiVersion: apps/v1
kind: Deployment  # Change ReplicaSet to Deployment
metadata:
  name: worker-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  replicas: 1  # This is the initial replica count; KEDA will adjust this
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmq.fullnameOverride }}.{{ .Values.rabbitmq.namespaceOverride }}.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 5; done;']
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          ports:
            - containerPort: {{ .Values.worker.port }}
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: keda-rabbitmq-secret  # Reference the secret for RabbitMQ connection
                  key: host
            - name: DATABASE_URL
              value: "mongodb+srv://{{ .Values.database.username }}:{{ .Values.database.password }}@cluster0.vfrom.mongodb.net/leetcode"
