apiVersion: apps/v1
kind: Deployment  # Change ReplicaSet to Deployment
metadata:
  name: worker-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1  # This is the initial replica count; KEDA will adjust this
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.rabbitmq.fullnameOverride }}.{{ .Values.rabbitmq.namespaceOverride }}.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 5; done;']
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          ports:
            - containerPort: {{ .Values.worker.port }}
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: keda-rabbitmq-secret  # Reference the secret for RabbitMQ connection
                  key: host
            - name: DATABASE_URL
              value: "mongodb+srv://{{ .Values.database.username }}:{{ .Values.database.password }}@cluster0.vfrom.mongodb.net/leetcode"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
  # labels:
  #   app.kubernetes.io/managed-by: "Helm"
  # annotations:
  #   meta.helm.sh/release-name:  {{ .Values.releasename }}
  #   meta.helm.sh/release-namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment  # Name of your worker deployment
  minReplicaCount: 1      # Minimum number of worker pods
  maxReplicaCount: 10     # Maximum number of worker pods
  cooldownPeriod:  300    # Cooldown period before scaling down
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        mode: QueueLength
        queueName: "judge"  # Your RabbitMQ queue
        value: "5"  # Number of messages in the queue to trigger scaling
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn
