keda:
  watchNamespace: "leetcode"
  namespace: keda

prometheus:
  namespace: "leetcode"
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: true
  pushgateway:
    enabled: true
  kubeStateMetrics:
    enabled: true

rabbitmq:
  fullnameOverride: "rabbitmq"
  namespaceOverride: "leetcode"
  auth:
    username: myuser1
    password: mypassword1
    #openssl rand -base64 32
    erlangCookie: 15e2cW7bCmoQEFGB1OojQjyTSqko8srW/pFmC0ofkXm4=
  replicas: 1
  service:
    type: ClusterIP

backend:
  image: dollysingh3192/leetcode-server:v7
  port: 3000

worker:
  image: dollysingh3192/leetcode-worker:v5
  port: 3001

database:
  username: dummy
  password: dummy

namespace: leetcode
releasename: leetcode

ignoreFiles: false # Change this to true to create templates